package main

import (
	"fmt"
	// "math"
)

// A Euler problem is a func with no params or return value
type Problem func() int

// Euler struct holding a map of problems by number and the current problem
type Euler struct {
	problems map[int]Problem
	current  int
}

// Add a Euler problem to our map
func (e *Euler) Add(f Problem) {
	e.problems[e.current] = f
	e.current++
}

// Call a Euler function by problem number
func (e *Euler) Call(index int) int {
	return e.problems[index]()
}

// Create a new Euler struct
func NewEuler() *Euler {
	return &Euler{
		problems: make(map[int]Problem),
		current:  1,
	}
}

// Problem one of project Euler
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.
func MultiplesOf3And5() int {
	sum := 0
	size := 1000

	for i := 3; i < size; i++ {
		if i%3 == 0 || i%5 == 0 {
			sum += i
		}
	}

	return sum
}

// Project two of project Euler
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
func EvenFibbonacciNumbers() int {
	a, b := 1, 1
	accum := 0

	for a+b < 4000000 {
		c := a + b

		if c%2 == 0 {
			accum += c
		}

		a, b = b, c
	}

	return accum
}

// Project three of project Euler
// The prime factors of 13195 are 5, 7, 13 and 29.
// What is the largest prime factor of the number 600851475143
func LargestPrimeFactor() int {
	return 0
}

func main() {
	e := NewEuler()

	e.Add(MultiplesOf3And5)
	e.Add(EvenFibbonacciNumbers)
	e.Add(LargestPrimeFactor)

	fmt.Printf("The answer to problem 1 is %d\n", e.Call(1))
}
